apiVersion: batch/v1
kind: Job
metadata:
  name: aurin-harvester
spec:
  template:
    metadata:
      labels:
        app: aurin-harvester
    spec:
      ttlSecondsAfterFinished: 0
      imagePullSecrets:
      - name: "docker.pkg.github.com"
      containers:
      - name: aurin-harvester
        image: "docker.pkg.github.com/cloud-71/aurin-harvester/aurin-harvester:23"
        env:
          - name: COUCHDB_HOST
            value: "couchdb-couchdb.default.svc.cluster.local:5984"
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: couchdb-couchdb
                key: adminPassword
          - name: DATASET_ID
            value: "aurin:datasource-VIC_Govt_CSA-UoM_AURIN_DB_csa_family_violence_family_incident_rate_lga_jul2013_jun2018"
          - name: DATASET_NAME
            value: "domestic_violence_vic"
        command: ["python"]
        # <kubectl apply --help> doesn't show any options to pass args into the config file, so its hardcoded for now
        args: ["aurinapi.py", "-s", "admin:$(COUCHDB_PASSWORD)", "$(COUCHDB_HOST)", "$(DATASET_NAME)", "-ad", "$(DATASET_ID)"]
      restartPolicy: OnFailure
