apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-harvester-deployment
  labels:
    app: twitter-harvester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-harvester
  template:
    metadata:
      labels:
        app: twitter-harvester
    spec:
      imagePullSecrets:
      - name: "docker.pkg.github.com"
      containers:
      - name: twitter-harvester
        image: "docker.pkg.github.com/cloud-71/twitter-harvester/twitter-harvester:11"
        env:
          - name: COUCHDB_HOST
            value: "couchdb-couchdb.default.svc.cluster.local"
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: couchdb-couchdb
                key: adminPassword
          - name: COUCHDB_DB_NAME
            value: "twitter_data"
