apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-harvester-search-deployment
  labels:
    app: twitter-harvester-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-harvester-search
  template:
    metadata:
      labels:
        app: twitter-harvester-search
    spec:
      imagePullSecrets:
      - name: "docker.pkg.github.com"
      containers:
      - name: twitter-harvester-search
        image: "docker.pkg.github.com/cloud-71/twitter-harvester/twitter-harvester:28"
        env:
          - name: COUCHDB_HOST
            value: "couchdb-couchdb.default.svc.cluster.local"
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: couchdb-couchdb
                key: adminPassword
          - name: COUCHDB_DB_NAME
            value: "twitter_data"
          # Twitter related tokens. Store all of them as secrets for safety
          - name: CONSUMER_TOKEN
            valueFrom:
              secretKeyRef:
                name: consumer-token
                key: token
          - name: CONSUMER_SECRET
            valueFrom:
              secretKeyRef:
                name: consumer-secret
                key: secret
          - name: ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: access-token
                key: token
          - name: ACCESS_SECRET
            valueFrom:
              secretKeyRef:
                name: access-secret
                key: secret
          - name: DESIGNATION
            value: "search"

          

