k3s_version: v1.18.2-rc4+k3s1
ansible_user: debian
master_ip: "{{ groups['master'][0] }}"
extra_k3s_node_args: "--docker"
extra_k3s_args: "--docker --write-kubeconfig-mode 644 --disable traefik --kube-apiserver-arg=enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,PodPreset --kube-apiserver-arg=runtime-config=settings.k8s.io/v1alpha1=true"
proxy_env:
  HTTP_PROXY: "http://wwwproxy.unimelb.edu.au:8000/"
  HTTPS_PROXY: "http://wwwproxy.unimelb.edu.au:8000/"
  http_proxy: "http://wwwproxy.unimelb.edu.au:8000/"
  https_proxy: "http://wwwproxy.unimelb.edu.au:8000/"
  no_proxy: "localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
