---

- name: Bootstrap the K3s cluster
  environment:
    INSTALL_K3S_EXEC: "server {{ extra_k3s_args }}"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  shell: "/tmp/k3s-install.sh"

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Read node-token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store node-token
  set_fact:
    token: "{{ node_token.content | b64decode | trim }}"

- name: Make sure K3s is running
  systemd:
    state: started
    name: k3s
