---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: Legacy iptables
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: Configure proxy
  lineinfile:
    dest: '/etc/environment'
    regexp: '^{{ item.key }}\ ?='
    line: "{{ item.key }}='{{ item.value }}'"
  with_dict:
    "{{ proxy_env }}"

- name: Configure Docker proxy
  copy:
    src: docker.service.d
    dest: /etc/systemd/system/

- name: Install Docker
  apt:
    name: docker.io
    state: present
