apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- target:
    kind: HelmChart
    name: couchdb
  patch: |-
    kind: HelmChart
    metadata:
      name: couchdb
    spec:
      set:
        service.type: "LoadBalancer"
        ingress.enabled: "true"
