apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../cloud
- resources/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
- resources/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
- resources/cinder-csi-plugin/cinder-csi-nodeplugin-rbac.yaml
- resources/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
- resources/cinder-csi-plugin/csi-cinder-driver.yaml
- resources/storageclass.yml
generators:
- barbican-secret-generator.yml
patches:
- patch: |-
    kind: HelmChart
    metadata:
      name: couchdb
    spec:
      set:
        persistentVolume.enabled: "true"
        persistentVolume.size: "50Gi"
        persistentVolume.storageClass: "csi-sc-cinderplugin"
  target:
    kind: HelmChart
    name: couchdb
