apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../cloud
- cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
- cinder-csi-plugin/cinder-csi-controllerplugin.yaml
- cinder-csi-plugin/cinder-csi-nodeplugin-rbac.yaml
- cinder-csi-plugin/cinder-csi-nodeplugin.yaml
- cinder-csi-plugin/csi-cinder-driver.yaml
- cinder-csi-plugin/csi-secret-cinderplugin.yaml
- storageclass.yml
patches:
- target:
    kind: HelmChart
    name: couchdb
  patch: |-
    kind: HelmChart
    metadata:
      name: couchdb
    spec:
      set:
        persistentVolume.enabled: "true"
        persistentVolume.size: "50Gi"
        persistentVolume.storageClass: "csi-sc-cinderplugin"
