# This YAML file contains secret objects,
# which are necessary to run csi cinder plugin.

kind: Secret
apiVersion: v1
metadata:
  name: cloud-config
  namespace: kube-system
data:
  cloud.conf: "W0dsb2JhbF0KYXV0aC11cmw9aHR0cHM6Ly9rZXlzdG9uZS5yYy5uZWN0YXIub3JnLmF1OjUwMDAvdjMvCmFwcGxpY2F0aW9uLWNyZWRlbnRpYWwtaWQ9YTA0Njc3MTYxMDNlNGIyNWI5NThmYzVhMTQyMjMzOTIKYXBwbGljYXRpb24tY3JlZGVudGlhbC1zZWNyZXQ9Q1BWejZ6Sm5ZRkg2UWUzMklIOGtTdlEwME9zcC15bTRUVW9wZC1RejVMYkVMSHJNQ3lXSmJyTVdzdmtrWjJNc0FwY2ZDYkZlbUhWYmo1RjJHOXdQSHcKdXNlci1pZD0yMjRjOTU2NTcwYjI0Yjc4OGExMDE0N2JmNDBiZWQ3YwpyZWdpb249TWVsYm91cm5lCg=="
  # ^ created using `base64 -w0 cloud.conf`
  # the application credential therein was created using
  # `openstack application credential create volume-mounts`
