---

- name: Join the K3s cluster
  environment:
    K3S_URL: "https://{{ master_ip }}:6443"
    K3S_TOKEN: "{{ hostvars[groups['master'][0]]['token'] }}"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  shell: "/tmp/k3s-install.sh {{ extra_k3s_node_args }}"
