apiVersion: group71/v1
kind: BarbicanSecret
metadata:
  name: barbican-secret-generator
secrets:
  - name: docker.pkg.github.com
    key: .dockerconfigjson
    type: kubernetes.io/dockerconfigjson
  - name: aurin-token
    key: password
  - name: consumer-token
    key: token
  - name: consumer-secret
    key: secret
  - name: access-token
    key: token
  - name: access-secret
    key: secret