apiVersion: group71/v1
kind: BarbicanSecret
metadata:
  name: barbican-secret-generator
secrets:
  - name: docker.pkg.github.com
    key: .dockerconfigjson
    type: kubernetes.io/dockerconfigjson
  - name: aurin_token
    namespace: kube-system

 