apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/aurin.yml
- resources/couchdb.yml
- resources/haproxy-ingress.yml
- resources/twitter-harvester.yml
- resources/web-app.yml
generators:
- barbican-secret-generator.yml
