apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      imagePullSecrets:
      - name: "docker.pkg.github.com"
      containers:
      - name: web-app
        image: "docker.pkg.github.com/cloud-71/web-app/web-app:11"
        ports:
        - containerPort: 3000
        env:
          - name: COUCHDB_HOST
            value: "couchdb-couchdb.default.svc.cluster.local:5984"
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: couchdb-couchdb
                key: adminPassword

---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-app
spec:
  backend:
    serviceName: web-app
    servicePort: 80
