apiVersion: batch/v1
kind: Job
metadata:
  name: aurin-harvester
spec:
  template:
    metadata:
      labels:
        app: aurin-harvester
    spec:
      containers:
        - name: 
          image: perl
          command: ["perl"]
          args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
        # Do not restart containers after they exit
        restartPolicy: Never
      imagePullSecrets:
      - name: "docker.pkg.github.com"
      containers:
      - name: aurin-harvester
        image: "docker.pkg.github.com/cloud-71/aurin-harvester/aurin-harvester:1"
        ports:
        - containerPort: 3000
        env:
          - name: COUCHDB_HOST
            value: "couchdb-couchdb.default.svc.cluster.local:5984"
          - name: DATASET_ID
            value: "aurin:datasource-VIC_Govt_CSA-UoM_AURIN_DB_csa_family_violence_family_incident_lga_jul2013_jun2018"
        command: ["python"]
        # just checking <kubectl apply --help> doesn't show any options to pass args into the config file, so its hardcoded for now
        args: ["aurinapi.py", "-s", "$(COUCHDB_HOST)", "-ad", "$(DATASET_ID)"] 
        restartPolicy: Never
