apiVersion: batch/v1
kind: Job
metadata:
  name: aurin-harvester
spec:
  template:
    metadata:
      labels:
        app: aurin-harvester
    spec:
      imagePullSecrets:
      - name: "docker.pkg.github.com"
      containers:
      - name: aurin-harvester
        image: "docker.pkg.github.com/cloud-71/aurin-harvester/aurin-harvester:latest"
        ports:
        - containerPort: 3000
        env:
          - name: COUCHDB_HOST
            value: "couchdb-couchdb.default.svc.cluster.local:5984"
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: couchdb-couchdb
                key: adminPassword
          - name: DATASET_ID
            value: "aurin:datasource-VIC_Govt_CSA-UoM_AURIN_DB_csa_family_violence_family_incident_lga_jul2013_jun2018"
        command: ["python"]
        # <kubectl apply --help> doesn't show any options to pass args into the config file, so its hardcoded for now
        args: ["aurinapi.py", "-s", "admin:$(COUCHDB_PASSWORD)","$(COUCHDB_HOST)", "-ad", "$(DATASET_ID)"] 
        restartPolicy: Never
