---
- hosts: all
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Wait for connection from the hosts
      wait_for_connection:
        connect_timeout: 5
        delay: 5
        sleep: 10
        timeout: 60

- hosts: k3s-cluster
  gather_facts: yes
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: prereq }
    - { role: download }

- hosts: master
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: k3s/master }

- hosts: node
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: k3s/node }
