---

- hosts: k3s-cluster
  gather_facts: yes
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: prereq }
    - { role: download }

- hosts: master
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: k3s/master }

- hosts: node
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: k3s/node }
