---
- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for connection from the hosts
      wait_for_connection:
        connect_timeout: 5
        delay: 5
        sleep: 10
        timeout: 180

- hosts: k3s-cluster
  gather_facts: yes
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: prereq }
    - { role: download }

- hosts: master
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: k3s/master }

- hosts: node
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: k3s/node }

- hosts: localhost
  environment:
    KUBECONFIG: '${HOME}/group71_kubeconfig'
  tasks:
    - name: Replace localhost entry with master IP
      replace:
        path: ~/group71_kubeconfig
        regexp: '127\.0\.0\.1'
        replace: "{{ master_ip }}"
    - command: 'echo export KUBECONFIG=$KUBECONFIG'
      register: output1

    - debug:
        msg:
          - "{{ output1.stdout }}"

- hosts: localhost
  tasks:
    - name: Put manifests in auto-deploy folder
      # what is this:
      # 1. run kustomize to combine all deployment manifests to stdout
      # 2. broadly, use: "ssh [ip] 'cat > location'" to send it to remote location
      # for more info, see my log at https://trello.com/c/TiHnO3rA/52-setup-auto-deploying-manifests#comment-5ec67fb711009e2d36a83b92
    
      shell: kustomize build kubernetes/cloud | ssh -i ~/.ssh/id_group71 {{ansible_user}}@{{ groups['master'][0] }} "sudo sh -c 'cat > /var/lib/rancher/k3s/server/manifests/combinedManifests.yml'" 
      args:
        chdir: ..